### PR TITLE
Add layer popups

### PR DESCRIPTION
**Pull request by mmcfarland**
### Overview
Adds popups with dynamic feature content associated with the selected dropdown vars for tracts and msa markers.

### Notes
* This is pointing to merge into the Charts branch, because it has significantly updated code
* I messed with some table names to get the appropriate variables for the popup, but I don't know which are technically the latest
* Popups are crude, but are extracted into templates in `index.html`
* The format renderers which I added probably need to be extended, but I wasn't sure what all of the field types were representing.
* I removed some svg styling that was overriding the Leaflet layer styles
* Selecting a new variable reloads the entire MSA tract layer, including geometries, which can be very slow and is unnecessary if we just get all the attributes at once.  This is the existing behavior and I didn't have time to adjust it in this PR.  It works, but could be made faster.

### Demo
image

image

### CODE REVIEW

**Comment by CloudNiner** [comment]
@simonkassel can you answer the comment above from Matt: "I messed with some table names to get the appropriate variables for the popup, but I don't know which are technically the latest"

**Comment by simonkassel** [comment]
@mmcfarland @CloudNiner yeah this is a good point to clarify. The most up-to-date table names will always be: **msa_change_transit_vars** for the msa-level data used in the graduated symbol maps, **tract_demographic_vars** for the census tract level data used in the tract choropleth maps, and **msa_yearly_transit_vars** for the time series chart. I understand the naming convention is a little confusing but any table with a **_v#** suffix is an older version. Let me know if that's not clear.

**Comment by mmcfarland** [comment]
Yep, looks like the attributes I need are in the base table, but just under different names.  I'll update the table and fields and add a new commit.

**Comment by CloudNiner** [comment]
Updated to use current table. Going to rebase to resolve merge conflict then merge.

**Pull request merged**
