### PR TITLE
Charts -- Basic Implementation

### PR DESCRIPTION
**Pull request by CloudNiner**
~~This is very much a WIP, but putting this up here so you can all see the changes being made. Still haven't started the second chart.~~

Still pretty WIP, but there's a bunch of changes here, and most of the remaining work is tweaks to functionality, bugfixing and adding QoL items such as legends/colors/etc. I'd like to get this looked at and merged so you have a better sense of what still needs to be done.

Also implemented the zoom/pan when the MSA dropdown is changed, to properly zoom to an MSA or zoom back out to national level if "National Average" is selected.

Some of the zoom/pan/popup/layer switch operations are busted, which is at least partially due to the mismatch in the names we're using as selectors across the different tables. I expect at least a few of the problems to be resolved once #49 is addressed (after this PR is merged).

## Demo

Initial state (first chart blank, haven't allowed case where only one axis in use yet):
screen shot 2017-11-08 at 14 26 56

After selecting an item in chart 1 list:
screen shot 2017-11-08 at 14 27 05

After selecting an MSA in the dropdown:
screen shot 2017-11-08 at 14 27 15

After selecting a new layer in map dropdown (charts are unaffected):
screen shot 2017-11-08 at 14 27 26

### CODE REVIEW

**Comment by eneedham** [comment]
Demo looks good. Only question - in the first chart: will we be able to view it before the second variable is selected (only using one y-axis)?

**Comment by CloudNiner** [comment]
Yes, should be doable. Would be faster to just set a second default variable, such as "Average Ridership" and not give the user the option to choose the second but either strategy is fine.

Either way, going to fix as part of a followup "chart tweaks" PR. 

If you have colors you'd like to use for the two chart's lines, those could be sent to me awhile. Hex or RGB is fine.

**Comment by eneedham** [comment]
Daniel is getting you five hex codes for the charts.

**Comment by dmcglone** [comment]
Total Ridership: #3165f0
avg_fare: #f03365
pop_change: #bd33f0
upt_rail_change: #f0bd33
variable: #65f033

**Comment by CloudNiner** [comment]
@dmcglone I believe I applied your selections appropriately, lmk if changes are necessary:

screen shot 2017-11-08 at 16 28 02

**Pull request merged**
